### PR TITLE
Unskip tests

### LINKED ISSUE #310: Re-enable tests broken due to Microsoft.NETCore.App
Tracking issue: https://github.com/dotnet/cli/issues/5172

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Fixes #310.

### CODE REVIEW

File: test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs [hunk 1]
```diff
@@ -84,7 +84,7 @@ public Task Localization_ResourcesInFolder_ReturnLocalizedValue_AllOS()
                 "http://localhost:5074",
                 "ResourcesInFolder",
                 "fr-FR",
-                "Bonjour from StartupResourcesInFolder Bonjour from Test in resources folder Bonjour from Customer in resources folder Bonjour from Test in resources folder");
```
Comment (pranavkm) [inline test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs]: what happened here?

Comment (ryanbrandenburg) [inline test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs]: This was a change that we made to all "ResourcesInFolder" tests that was missed in this instance because the test didn't fail.
