### PR TITLE
Use existing CultureInfo

### LINKED ISSUE #203: Custom Cultures not working with RequestLocalizationMiddleware
### Title
Custom Cultures not working with `RequestLocalizationMiddleware`

### Functional impact
It is impossible to use custom settings for Cultures when using `RequestLocalizationMiddleware`

### Minimal repro steps
- Create custom CultureProvider
```
public class SampleCultureProvider : RequestCultureProvider
{
    public override Task<ProviderCultureResult> DetermineProviderCultureResult(HttpContext httpContext)
    {
        var providerResultCulture = new ProviderCultureResult("en-US");
        return Task.FromResult(providerResultCulture);
    }
}
```
- Create custom localization options (changed CurrencySymbol in this example)
```
private RequestLocalizationOptions CreateLocalizationOptions()
{
    var supportedCulturesList = new List<CultureInfo>
    {
        new CultureInfo("en-US", true) { NumberFormat = { CurrencySymbol = "kr" } }
    };

    var localizationOptions = new RequestLocalizationOptions
    {
        SupportedCultures = supportedCulturesList,
        SupportedUICultures = supportedCulturesList
    };
            
    localizationOptions.RequestCultureProviders.Clear();
    localizationOptions.RequestCultureProviders.Add(new SampleCultureProvider());
    return localizationOptions;
}
```
- Add RequestLocalizationMiddleware using these options
```
public void Configure(IApplicationBuilder app)
{
    app.UseIISPlatformHandler();

    var globalizationOptions = this.CreateLocalizationOptions();
    app.UseRequestLocalization(globalizationOptions, new RequestCulture(new CultureInfo("en-GB")));

    (...)
}
```
- display text using currency formatting
```
public void Configure(IApplicationBuilder app)
{
    (...)
    app.Run(async (context) =>
    {
        await context.Response.WriteAsync(123.ToString("C"));
    });
}
```
Sample solution reproducing this bug attached: [RequestLocalizationMiddlewareBug.zip](https://github.com/aspnet/Localization/files/98886/RequestLocalizationMiddlewareBug.zip)

### Expected result
Changed currency symbol should be displayed: **kr123.00**

### Actual result
Default currency symbol is used: **$123.00**

### Further technical details
Problem is - most likely - caused by `CultureInfoCache`. When `GetCultureInfo` is called `supportedCultures` are checked to see whether requested culture is supported. 

```
if (name == null || supportedCultures == null ||
    !supportedCultures.Any(supportedCulture => string.Equals(supportedCulture.Name, name, StringComparison.OrdinalIgnoreCase)))
{
    return null;
}
```
Later on, however, instead of adding provided culture to the cache new culture is created with a given name and added
```
var entry = _cache.GetOrAdd(name, n =>
{
    try
    {
        return new CacheEntry(CultureInfo.ReadOnly(new CultureInfo(n)));
    }
    catch (CultureNotFoundException)
    {
        (...)
    }
});
```
I guess that using
```
var culture = supportedCultures.Single(supportedCulture => string.Equals(supportedCulture.Name, name, StringComparison.OrdinalIgnoreCase));
return new CacheEntry(CultureInfo.ReadOnly(culture));

```
instead of
```
return new CacheEntry(CultureInfo.ReadOnly(new CultureInfo(n)));
```
should fix this

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Fixes #203. Given this fix `CultureInfoCache` could just as a easily be a helper function on the middleware since it's no longer an actual cache, but I wasn't sure if we would be able to get rid of the whole class like that. @DamianEdwards would that be possible?

### CODE REVIEW

File: src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs [hunk 1]
```diff
@@ -14,8 +13,6 @@ namespace Microsoft.Extensions.Globalization
     /// </summary>
     public static class CultureInfoCache
```
Comment (pranavkm) [inline src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs]: public API, so you can't remove it

File: src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs [hunk 2]
```diff
@@ -30,38 +27,18 @@ public static CultureInfo GetCultureInfo(string name, IList<CultureInfo> support
...
-                }
-            });
-
-            return entry.CultureInfo;
-        }
-
-        private class CacheEntry
-        {
-            public CacheEntry(CultureInfo cultureInfo)
+            var culture = supportedCultures.SingleOrDefault(
```
Comment (pranavkm) [inline src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs]: `FirstOrDefault`

File: test/Microsoft.Extensions.Globalization.CultureInfoCache.Tests/CultureInfoCacheTest.cs [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+namespace Microsoft.Extensions.Globalization
+{
+    public class CultureInfoCacheTest
+    {
+        [Fact]
+        public void CultureInfoCache_ReturnsModifiedCultureInfo()
+        {
+            // Arrange
+            var supportedCultures = new List<CultureInfo> {
```
Comment (pranavkm) [inline test/Microsoft.Extensions.Globalization.CultureInfoCache.Tests/CultureInfoCacheTest.cs]: `{` on the next line.

File: src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs [hunk 4]
```diff
@@ -30,38 +27,18 @@ public static CultureInfo GetCultureInfo(string name, IList<CultureInfo> support
         {
             // Allow only known culture names as this API is called with input from users (HTTP requests) and
             // creating CultureInfo objects is expensive and we don't want it to throw either.
-            if (name == null || supportedCultures == null ||
```
Comment (pranavkm) [inline src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs]: Could you modify the `<returns>` on this method to say ...`or <null> if a match` (the if is missing)

**Comment by ryanbrandenburg** [comment]
:up::date: @DamianEdwards is OK with obsoleting it for now and just not using it anywhere. I've built that in now.

File: Localization.sln [hunk 5]
```diff
@@ -31,9 +31,9 @@ Project("{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}") = "LocalizationWebsite", "test
 EndProject
 Project("{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}") = "Microsoft.AspNetCore.Localization.FunctionalTests", "test\Microsoft.AspNetCore.Localization.FunctionalTests\Microsoft.AspNetCore.Localization.FunctionalTests.xproj", "{B1B441BA-3AC8-49F8-850D-E5A178E77DE2}"
 EndProject
-Project("{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}") = "ResourcesClassLibraryWithAttribute", "test\ResourcesClassLibraryWithAttribute\ResourcesClassLibraryWithAttribute.xproj", "{F27639B9-913E-43AF-9D64-BBD98D9A420A}"
+Project("{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}") = "ResourcesClassLibraryNoAttribute", "test\ResourcesClassLibraryNoAttribute\ResourcesClassLibraryNoAttribute.xproj", "{939FFC22-82BD-47B3-9F6C-89C62AD0A0F7}"
```
Comment (hishamco) [inline Localization.sln]: Is this change a part of the previous PR #283?!! correct me if I'm wrong

File: src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs [hunk 6]
```diff
@@ -157,13 +157,31 @@ private static void SetCurrentThreadCulture(RequestCulture requestCulture)
...
+        {
+            // Allow only known culture names as this API is called with input from users (HTTP requests) and
+            // creating CultureInfo objects is expensive and we don't want it to throw either.
+            if (name == null || supportedCultures == null)
+            {
+                return null;
+            }
+            var culture = supportedCultures.FirstOrDefault(
+                supportedCulture => string.Equals(supportedCulture.Name, name, StringComparison.OrdinalIgnoreCase));
+            if (culture == null)
```
Comment (hishamco) [inline src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs]: Please add a new line here

File: src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs [hunk 7]
```diff
@@ -12,6 +12,7 @@ namespace Microsoft.Extensions.Globalization
     /// <summary>
     /// Provides read-only cached instances of <see cref="CultureInfo"/>.
     /// </summary>
+    [Obsolete("This type is obsolete and will be removed in a future version.")]
```
Comment (hishamco) [inline src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs]: :+1:

File: test/ResourcesClassLibraryNoAttribute/ResourcesClassLibraryNoAttribute.xproj [hunk 8]
```diff
@@ -0,0 +1,18 @@
+﻿<?xml version="1.0" encoding="utf-8"?>
```
Comment (hishamco) [inline test/ResourcesClassLibraryNoAttribute/ResourcesClassLibraryNoAttribute.xproj]: Same for the first comment

File: test/ResourcesClassLibraryWithAttribute/ResourcesClassLibraryWithAttribute.xproj [hunk 9]
```diff
@@ -0,0 +1,18 @@
+﻿<?xml version="1.0" encoding="utf-8"?>
```
Comment (hishamco) [inline test/ResourcesClassLibraryWithAttribute/ResourcesClassLibraryWithAttribute.xproj]: Same for the first comment

**Comment by DamianEdwards** [comment]
@ryanbrandenburg as discussed, is any change required to the middleware to ensure it uses the actual supplied instance of `CultureInfo` specified as being the default?

**Comment by ajaybhargavb** [comment]
:shipit: after removing all the unrelated changes.

**Comment by ryanbrandenburg** [comment]
@DamianEdwards it appears we already used the existing instance of `CultureInfo` for `DefaultRequestCulture` so no change needed there.

File: Localization.sln (hunk 5 above)
Comment (ryanbrandenburg) [inline Localization.sln]: The SLN mearly got jumbled in my rebase. The xproj items got accidentally included and will be removed.

Comment (hishamco) [inline Localization.sln]: I see

File: src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs [hunk 10]
```diff
@@ -12,6 +12,7 @@ namespace Microsoft.Extensions.Globalization
...
     public static class CultureInfoCache
```
Comment (hishamco) [inline src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs]: Do we really need this class anymore? or is it there for backward compatibility?

**Comment by hishamco** [comment]
Can we have a unit test, to make sure that's fix #203?

File: src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs (hunk 10 above)
Comment (DamianEdwards) [inline src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs]: We can't remove public API (including types) in minor releases, so we have to keep it around until v2.
